name: STEC Monitoring build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2

            - name: Install latest stable
              uses: actions-rs/toolchain@v1
              with:
                    toolchain: stable
                    override: true
                    components: rustfmt, clippy

            - name: Build
              run: cargo build --release

            - name: Run tests
              run: cargo test
