[package]
name = "rocket-fuel"
version = "0.1.0"
authors = ["Stefan Schick <stefan.schick@stecug.de>"]
edition = "2018"
description = "Fuel to speed up the development of rocket web apps"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
rocket_contrib = { version = "0.4.7", default-features = true, features = ["tera_templates"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "uuidv07", "chrono"] }
rusqlite = "0.25.0"

uuid = { version = "0.8.2", features = ["serde", "v4"]}
clap = "2.33.3"
log = "0.3.9"
env_logger = "0.8.3"

serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.61"

aes = "0.6.0"
block-modes = "0.7.0"
hex = "0.4.3"

sendgrid = "0.17.0"
image-convert = "0.10.2"